Blog.create!([
  {name: "Carol e suas baby-bobeiras", url: "http://www.carolesuasbabybobeiras.com/", fans: 2, about: "Carol. Bobinha. Mommy do Lucas. Jornalista. Quase fotógrafa. Carioca. Moradora da Argentina. Blogueira.", uf: ""},
  {name: "Bem que se quis", url: "http://www.bemquesequis.com/", fans: 2, about: "Meu nome é Denise, sou jornalista e nascida e criada em Florianópolis. Em 2009 conheci o Diego, em pleno Carnaval.\r\n\r\nNa época eu morava no Tocantins e ele era representante comercial em Florianópolis. Como o namoro era recente, eu acabei aceitando uma proposta de emprego em São Paulo, e ele voltou para sua cidade natal. Namoramos à distância por quase dois anos, até que finalmente consegui um emprego legal em Florianópolis, onde ele já estava morando havia alguns meses.\r\n\r\nDesde então, passei a agradecer todos os dias por finalmente conseguirmos ficar juntos.\r\n\r\nNo final de 2011 decidimos que era hora de aumentar a família, e eu criei este blog para registrar essa trajetória. :)\r\n\r\nDepois de uma perda em fevereiro/2012, em março engravidamos novamente e agora pra valer! Descobrimos em um teste de farmácia no dia 25/04, dia do Show do Paul McCartney em Floripa.\r\n\r\nNosso maior presente chegou a uma semana do Natal, no dia 17 de dezembro de 2012, pesando 4,015 kg e medindo 52 centímetros.", uf: ""},
  {name: "Diiirce", url: "http://diiirce.com.br", fans: 2, about: "Ainda se fazem mães como antigamente", uf: ""},
  {name: "Mamãe Blogueira", url: "http://mamaeblogueira.com/", fans: 5, about: "Publicitária, que trabalha com vendas, apaixonada por moda, com vontade de conhecer o mundo e descobriu que está grávida.\r\n\r\nMeu nome é Priscila Leão, tenho 26 anos e moro em Recife.\r\n\r\nResolvi fazer do blog um cantinho pra dividir com o mundo o amor de uma mãe por uma filha que está a caminho.", uf: ""},
  {name: "Mães Online", url: "http://maesonline.blogspot.com.br/", fans: 5, about: "O Blog para as mulheres que estão iniciando a maior viagem de suas vidas: tornarem-se mães! Por Flávia Corazza", uf: ""},
  {name: "Aprendiz de mãe", url: "http://aprendiz-de-mae.blogspot.com.br/", fans: 10, about: "\"Para que a gente escreve, se não é para juntar nossos pedacinhos?\"\r\n\r\n(Eduardo Galeano)", uf: ""},
  {name: "Madre Mia", url: "http://madremia.com.br", fans: 2, about: "As (loucas) aventuras de uma mãe brasileira e seu pequeno espanhol – no Brasil", uf: ""},
  {name: "Para Beatriz", url: "http://parabeatriz.com/", fans: 3, about: "Um blog sobre maternidade com uma visão feminista. Blog escrito em especial para a Beatriz, para ensinar para ela uma das coisas mais importante que eu posso ensinar: feminismo.\r\n \r\nSou Isabela Kanupp, tenho 23 anos, sou feminista, geminiana, teimosa. Adoro escrever, fotografar e ler. Sou uma acumuladora de conhecimentos. Já plantei uma árvore, já tive uma filha e estou escrevendo um livro.\r\nEscrever para mim sempre foi como uma terapia, já foi trabalho e hoje vejo como uma forma importantíssima de ajudar a mim e a outras pessoas.", uf: ""},
  {name: "Marmita Baby", url: "http://marmitababy.blogspot.com.br/", fans: 1, about: "Marmita Baby são vídeos com receitas de comidinhas para bebês e crianças e informações sobre alimentação infantil.", uf: ""},
  {name: "Vida de Gestante e mãe", url: "http://www.vidadegestanteemae.com.br/", fans: 3, about: "De repente me vi grávida! Sempre quis ser mãe nova e desde quando casei pensava em engravidar, mas não imaginei que seria tão depressa. No começo foi o susto, mas depois foi muita, muita alegria! Como eu amo escrever, decidi que faria um blog para contar  sobre esta fase tão nova para mim. Rapidamente conheci muitas outras futuras mamães que começaram a comentar e me estimular a escrever cada dia mais.\r\nAssim, passei a publicar matérias que considero relevantes e com elas foram aparecendo leitores querendo contar suas histórias e trocar experiências, fazendo do blog o que ele é hoje. Um espaço não só meu, mas de todos que se interessam pela maternidade/paternidade, que querem dividir suas dicas ou procurar informações sobre diversos assuntos ligados ao tema.", uf: ""},
  {name: "Gemelares", url: "gemelares.com.br", fans: 31, about: "Quando estava grávida dos gêmeos, observei a falta de realidade dessas futuras mamães. Precisava existir tudo em apenas um lugar. ", uf: "Rio de Janeiro"},
  {name: "Mãe Nota Dez", url: "http://maenotadez.com.br/", fans: 1, about: "A maioria das mulheres, quando está grávida, lê diversos livros sobre como cuidar do seu bebê depois que ele nascer. O curioso é que, quando chega em casa com o filho nos braços, a maioria esquece de tudo o que leu e não sabe muito o que fazer, e tem que consultar tudo de novo.\r\n\r\nPensando nisso, criamos o Mãe Nota Dez!, para compartilharmos assuntos interessantes e relevantes e gerar opiniões de mães que já tiveram seus filhos e querem compartilhar a experiência e ajudar as novas mamães. Tudo para você se tornar uma mãe nota dez!\r\n\r\nRessaltamos aqui que ser uma mãe nota dez é saber o que é melhor para você e seu filho, descobrindo aos poucos o que vocês mais gostam, como vocês se ajeitam melhor.\r\n\r\nAproveitem!! Comentem e perguntem!\r\n\r\nAcesse também nosso grupo Dicas e ideias de mães e pais no Facebook.\r\n\r\nP.S.: Independentemente de você ter lido livros, blogs, guias na internet, folhetos etc., o importante é sempre consultar o pediatra ou o ginecologista que está te acompanhando. Somente eles poderão dar a melhor informação de que precisam.", uf: ""},
  {name: "Macetes de mãe", url: "http://www.macetesdemae.com", fans: 23, about: "O Macetes de Mãe começou com esse blog, no dia 02 de abril de 2012, menos de dois meses antes do meu filhote (a inspiração de tudo isso) nascer.\r\n\r\nNa época, a ideia parecia loucura até para mim, afinal, seria quase como ter dois filhos em casa, mas segui adiante e arrisquei. Escrevi feito doida enquanto o Léo não dava as caras e depois da sua chegada, entre uma mamada e outra, uma troca de fralda e outra, fui postando relatos das minhas experiências e descobertas no recém experimentado universo materno.\r\n\r\nPara minha surpresa, no meio daquela doideira toda, com um bebê em um braço e um laptop em outro, o Macetes de Mãe cresceu (não disse que era como um filho?)! Primeiro veio a Fanpage do MdM, cheia de dicas e inspirações sobre os mais variados assuntos dos universos materno e infantil, e em seguida, o Instagram, o Pinterest, o Twitter e o Google+.\r\n\r\nHoje, depois do Léo, o Macetes de Mãe é grande fonte de alegria e realização da minha vida. Tudo que compartilho aqui ou nos demais canais é escrito com muito cuidado e carinho, pensando sempre em facilitar a vida de mamães de primeira ou várias viagens.", uf: "São Paulo"},
  {name: "Minha mae que disse", url: "minhamaequedisse.com", fans: 1, about: "asfasf", uf: ""},
  {name: "Mamatraca", url: "http://mamatraca.com.br", fans: 3, about: "asgasgasgas", uf: ""},
  {name: "Blog da ti", url: "http://blogdati.com/", fans: 4, about: "aGJKHakJHGak a ghaksgak aj gas gkja hgakjg ", uf: ""}
])
